- hosts: task
  become: yes
  tasks:
  - name: Create new user
    tags: user
    user:
      name=user1
      groups=sudo
      shell=/bin/bash

  - name: Add SSH keys to host
    tags: user
    authorized_key:
      user: user1
      key: "{{ lookup('file', '/home/batpylli/.ssh/user1.pub') }}"
      path: /home/user1/.ssh/id_rsa.pub
      manage_dir: False
      state: present

  - name: Install postfix
    tags: init postfix
    apt:
      update_cache: yes
      name: postfix
      state: present

  - name: Drop postfix
    tags: drop postfix
    apt:
      name: postfix
      state: absent
